services:
  - type: web
    name: quizmaster-backend
    env: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
    # Add your environment variables in Render dashboard:
    # MONGODB_URI, JWT_SECRET, GROQ_API_KEY, FRONTEND_URL
